baseURL = 'https://prameykabra.me/'
languageCode = 'en-us'
title = 'Pramey Kabra'
theme = 'PaperMod'

googleAnalytics = "G-6ZN5ZJB3P1"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Pramey Kabra"
description = "Hi! I'm Pramey Kabra, a senior at Purdue University majoring in Computer Science and Data Science with a minor in Economics. My concentrations are Machine Intelligence and Database Systems. I'm the Head Teaching Assistant for seminar courses at The Data Mine at Purdue. I'm currently working on a NSF-funded research project with [I-Guide](https://iguide.illinois.edu/) at University of Illinois Urbana-Champaign and [Rosen Center for Advanced Computing](https://www.rcac.purdue.edu/) at Purdue University."
keywords = [
  "Pramey Kabra",
  "Portfolio",
  "Data Science",
  "Computer Science",
  "Purdue University"
]
author = "Pramey Kabra"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowBreadCrumbs = true
hideFooter = false

  [params.label]
  text = "Pramey Kabra"

  [params.homeInfoParams]
  Title = "Welcome! 👋"
  Content = "Hi! I'm Pramey, a graduate of Purdue University with a Bachelor's in Computer Science and Data Science."
  Content2 = "I am a System Engineer at [Eli Lilly and Company](https://lilly.com/) in the Manufacturing and Quality Global Quality Assurance team in Indianapolis, IN."
  Content3 = "If you would like to chat, please reach out to me at [kabrapramey@gmail.com](mailto:kabrapramey@gmail.com)."

  [[params.socialIcons]]
  name = "kabrapramey@gmail.com"
  url = "mailto:kabrapramey@gmail.com"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/kabrap/"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/kabrap"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 2
